
# PostgreSQL database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_service
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

# JPA configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
# Eureka client configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    prefer-ip-address: true